interface Env {
  STATS_READ_TOKEN?: string;
  STATS_ADMIN_USERNAME?: string;
  STATS_ADMIN_PASSWORD?: string;
  INFOGRAPHIC_API_KEY?: string;
  DEFAULT_LANGUAGE_API_KEY?: string;
  DEFAULT_MULTIMODAL_API_KEY?: string;
  MODEL_STATS_HASH_SECRET?: string;
}
